# Generated by Django 2.1 on 2019-02-27 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leet', '0007_create_event_types'),
        ('geo', '0011_drop_null_timezone'),
        ('job', '0020_load_skills_industries'),
        ('company', '0014_companyuser_candidates_statuses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('INVITED', 'Invited'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='INVITED', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=4000)),
                ('time_from', models.DateTimeField()),
                ('time_to', models.DateTimeField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='company.Company')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='job.Job')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='geo.Address')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to=settings.AUTH_USER_MODEL)),
                ('timezone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='geo.TimeZone')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='leet.EventType')),
            ],
        ),
        migrations.AddField(
            model_name='attendee',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendees', to='event.Event'),
        ),
        migrations.AddField(
            model_name='attendee',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
