# Generated by Django 2.1 on 2019-03-12 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='timezone',
            field=models.CharField(default='UTC', max_length=255, verbose_name='timezone'),
        ),
    ]
