# Generated by Django 2.1 on 2018-09-20 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('job_seeker', '0001_initial'),
        ('leet_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='leet_auth.ProxyUser', verbose_name='User'),
        ),
    ]
