# Generated by Django 2.1 on 2018-09-27 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_seeker', '0003_jobexperience'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('institution', models.CharField(max_length=256, verbose_name='institution')),
                ('field_of_study', models.CharField(max_length=256, verbose_name='field_of_study')),
                ('location', models.CharField(blank=True, max_length=256, verbose_name='location')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('is_current', models.BooleanField(default=False, verbose_name='is_current')),
                ('graduated', models.DateTimeField(blank=True, null=True, verbose_name='graduated')),
                ('licence_number', models.CharField(blank=True, max_length=100, verbose_name='licence_number')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='job_seeker.JobSeeker')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('institution', models.CharField(max_length=256, verbose_name='institution')),
                ('field_of_study', models.CharField(max_length=256, verbose_name='field_of_study')),
                ('location', models.CharField(blank=True, max_length=256, verbose_name='location')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('is_current', models.BooleanField(default=False, verbose_name='is_current')),
                ('degree', models.CharField(blank=True, choices=[('HIGH_SCHOOL', 'High School'), ('ASSOCIATES_DEGREE', 'Associates Degree'), ('BACHELORS_DEGREE', "Bachelor's Degree"), ('MASTERS_DEGREE', "Master's Degree"), ('PHD', 'PHD')], max_length=40, verbose_name='education')),
                ('date_from', models.DateTimeField(verbose_name='date_from')),
                ('date_to', models.DateTimeField(blank=True, null=True, verbose_name='date_to')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='job_seeker.JobSeeker')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
