# Generated by Django 2.1 on 2018-10-03 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_owner_and_publsh_date_datetime'),
        ('job_seeker', '0004_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savedjob_set', to='job.Job')),
                ('job_seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_jobs', to='job_seeker.JobSeeker')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='savedjob',
            unique_together={('job', 'job_seeker')},
        ),
    ]
