# Generated by Django 2.1 on 2018-10-09 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seeker', '0005_saved_jobs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseeker',
            name='travel',
            field=models.CharField(blank=True, choices=[('NO_TRAVEL', 'No Travel'), ('WILLLING_TO_TRAVEL', 'Willing To Travel')], max_length=40, verbose_name='travel'),
        ),
    ]
