# Generated by Django 2.1 on 2018-10-19 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seeker', '0007_relation_name_job_seeker'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobexperience',
            name='employment',
            field=models.CharField(blank=True, choices=[('FULL_TIME', 'Full Time'), ('PART_TIME', 'Part Time')], max_length=16, verbose_name='employment'),
        ),
    ]
