# Generated by Django 2.1 on 2018-10-23 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seeker', '0008_employment_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='is_public'),
        ),
    ]
