# Generated by Django 2.1 on 2018-10-31 10:08

from django.db import migrations
import leet.utils
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('job_seeker', '0010_auto_20181025_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseeker',
            name='photo',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to=leet.utils.get_photo_path, verbose_name='photo'),
        ),
    ]
