# Generated by Django 2.1 on 2018-11-05 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seeker', '0011_auto_20181031_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
