# Generated by Django 2.1 on 2018-11-20 10:50

from django.db import migrations, models


def update_travel_field(apps, schema_editor):
    JobSeeker = apps.get_model("job_seeker", "JobSeeker")
    JobSeeker.objects.filter(
        travel='WILLLING_TO_TRAVEL'
    ).update(travel='WILLING_TO_TRAVEL')


class Migration(migrations.Migration):

    dependencies = [
        ('job_seeker', '0013_add_cover_letter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseeker',
            name='travel',
            field=models.CharField(
                blank=True,
                choices=[('NO_TRAVEL', 'No Travel'), ('WILLING_TO_TRAVEL', 'Willing To Travel')],
                max_length=40, verbose_name='travel'),
        ),
        migrations.RunPython(update_travel_field)
    ]
