# Generated by Django 2.1 on 2018-11-26 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seeker', '0014_change_travel_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='about',
            field=models.TextField(blank=True, max_length=2000, verbose_name='about'),
        ),
    ]
