# Generated by Django 2.1 on 2018-12-10 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seeker', '0015_jobseeker_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='ban_status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('BANNED', 'Banned')], default='ACTIVE', max_length=16, verbose_name='ban_status'),
        ),
    ]
