# Generated by Django 2.1 on 2019-01-04 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_auto_20181210_0951'),
        ('job_seeker', '0017_nullable_for_job_seeker_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewJobSeeker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='profile_viewer', to='company.Company')),
                ('job_seeker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='viewed_profile', to='job_seeker.JobSeeker')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='viewjobseeker',
            unique_together={('job_seeker', 'company')},
        ),
    ]
