# Generated by Django 2.1 on 2019-01-15 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seeker', '0018_auto_20190104_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobexperience',
            name='description',
            field=models.TextField(blank=True, max_length=4000, null=True, verbose_name='description'),
        ),
    ]
