# Generated by Django 2.1 on 2019-01-25 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0014_companyuser_candidates_statuses'),
        ('job_seeker', '0019_max_length_for_job_experience_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedJobSeeker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('company_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.CompanyUser')),
                ('job_seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_seeker.JobSeeker')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='savedjobseeker',
            unique_together={('job_seeker', 'company_user')},
        ),
    ]
