# Generated by Django 2.1 on 2019-02-08 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0014_companyuser_candidates_statuses'),
        ('job_seeker', '0020_saved_job_seekers'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewjobseeker',
            name='company_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='viewed_job_seekers', to='company.CompanyUser'),
        ),
        migrations.AlterField(
            model_name='viewjobseeker',
            name='job_seeker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='job_seeker.JobSeeker'),
        ),
        migrations.AlterUniqueTogether(
            name='viewjobseeker',
            unique_together={('job_seeker', 'company', 'company_user')},
        ),
    ]
