# Generated by Django 2.1 on 2019-02-08 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_seeker', '0022_fill_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewjobseeker',
            name='company_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='viewed_job_seekers', to='company.CompanyUser'),
        ),
    ]
