# Generated by Django 2.1 on 2019-02-11 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0014_companyuser_candidates_statuses'),
        ('job_seeker', '0023_drop_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewjobseeker',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.Company'),
        ),
        migrations.AlterUniqueTogether(
            name='viewjobseeker',
            unique_together={('job_seeker', 'company_user')},
        ),
    ]
