# Generated by Django 2.1 on 2019-02-11 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_seeker', '0024_drop_company_from_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viewjobseeker',
            name='company',
        ),
    ]
