# Generated by Django 2.1 on 2019-02-12 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_seeker', '0025_remove_viewjobseeker_company'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='viewjobseeker',
            unique_together=set(),
        ),
    ]
