# Generated by Django 2.1 on 2019-02-14 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0020_load_skills_industries'),
        ('job_seeker', '0026_drop_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='industries',
            field=models.ManyToManyField(blank=True, to='job.Industry'),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='skills',
            field=models.ManyToManyField(blank=True, to='job.Skill'),
        ),
    ]
