# Generated by Django 2.1 on 2019-02-18 13:38

from django.db import migrations, models
import uuid


def set_guids(apps, schema_editor):
    JobSeeker = apps.get_model("job_seeker", "JobSeeker")
    job_seekers = JobSeeker.objects.all()
    for job_seeker in job_seekers:
        job_seeker.guid = uuid.uuid4()
        job_seeker.save()


class Migration(migrations.Migration):

    dependencies = [
        ('job_seeker', '0027_field_industries_and_blank_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='guid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='is_shared',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(set_guids),
    ]

