# Generated by Django 2.1 on 2019-02-28 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_seeker', '0029_guid_uniqueness'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobSeekerActivityReport',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('job_seeker.jobseeker',),
        ),
        migrations.CreateModel(
            name='JobSeekerRegistrationReport',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('job_seeker.jobseeker',),
        ),
    ]
