# Generated by Django 2.1 on 2019-03-12 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seeker', '0030_jobseekeractivityreport_jobseekerregistrationreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseeker',
            name='salary_max',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='salary_max'),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='salary_min',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='salary_min'),
        ),
    ]
