# Generated by Django 2.1 on 2019-03-21 09:45

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations

from job_seeker import search_vectors


def update_job_seeker_documents(apps, schema_editor):
    JobSeeker = apps.get_model("job_seeker", "JobSeeker")
    job_seekers = JobSeeker.objects.annotate(
        document=search_vectors.SEARCH_VECTOR,
        location_document=search_vectors.LOCATION_SEARCH_VECTOR,
    )
    for job_seeker in job_seekers:
        job_seeker.search_vector = job_seeker.document
        job_seeker.location_search_vector = job_seeker.location_document
        job_seeker.save(update_fields=['search_vector', 'location_search_vector'])


class Migration(migrations.Migration):

    dependencies = [
        ('job_seeker', '0031_auto_20190312_0754'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='location_search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='jobseeker',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='job_seeker__search__85a3e6_gin'),
        ),
        migrations.AddIndex(
            model_name='jobseeker',
            index=django.contrib.postgres.indexes.GinIndex(fields=['location_search_vector'], name='job_seeker__locatio_6eff46_gin'),
        ),
        migrations.RunPython(update_job_seeker_documents)
    ]
