# Generated by Django 2.1 on 2019-03-26 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seeker', '0032_auto_20190321_0945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseeker',
            name='salary_negotiable',
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='salary_public',
            field=models.BooleanField(default=False, verbose_name='salary_public'),
        ),
    ]
