# Generated by Django 2.1 on 2019-03-28 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_seeker', '0033_auto_20190326_0619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewjobseeker',
            name='company_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewed_job_seekers', to='company.CompanyUser'),
        ),
        migrations.AlterField(
            model_name='viewjobseeker',
            name='job_seeker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_seeker.JobSeeker'),
        ),
    ]
