# Generated by Django 2.1 on 2019-04-01 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seeker', '0034_auto_20190328_0625'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='is_password_set',
            field=models.BooleanField(default=True),
        ),
    ]
