# Generated by Django 2.1 on 2019-07-15 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seeker', '0035_jobseeker_is_password_set'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseeker',
            name='clearance',
            field=models.CharField(blank=True, choices=[('SECRET', 'Secret'), ('TOP_SECRET', 'Top Secret'), ('TOP_SECRET_SCI', 'Top Secret/SCI'), ('MBI', 'MBI'), ('PUBLIC_TRUST', 'Public Trust'), ('CONFIDENTIAL', 'Confidential'), ('UNCLASSIFIED', 'Unclassified'), ('', 'No selection')], max_length=40, null=True, verbose_name='clearance'),
        ),
    ]
