# Generated by Django 2.1 on 2018-09-20 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo', '0002_create_countries_and_states'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.CharField(blank=True, max_length=4000, verbose_name='description')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='phone')),
                ('fax', models.CharField(blank=True, max_length=32, verbose_name='fax')),
                ('website', models.CharField(blank=True, max_length=255, verbose_name='website')),
                ('email', models.CharField(blank=True, max_length=255, verbose_name='email')),
                ('address', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geo.Address')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
