# Generated by Django 2.1 on 2018-10-25 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_companyadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='companyadmin',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
