# Generated by Django 2.1 on 2018-10-31 10:08

from django.db import migrations, models
import django.db.models.deletion
import leet.utils
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0009_auto_20181025_0859'),
        ('company', '0003_auto_20181025_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='job.Industry'),
        ),
        migrations.AddField(
            model_name='company',
            name='photo',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to=leet.utils.get_photo_path, verbose_name='photo'),
        ),
    ]
