# Generated by Django 2.1 on 2018-11-08 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_rename_model_companyadmin_to_companyuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyuser',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_users', related_query_name='company_user', to='company.Company'),
        ),
        migrations.AlterField(
            model_name='companyuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_user', to='leet_auth.ProxyUser'),
        ),
    ]

    atomic = False
