# Generated by Django 2.1 on 2018-11-13 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seeker', '0012_auto_20181105_0616'),
        ('company', '0007_company_admin_to_company_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='purchased_job_seekers',
            field=models.ManyToManyField(to='job_seeker.JobSeeker'),
        ),
    ]
