# Generated by Django 2.1 on 2018-12-12 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_purchaised_job_seekers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'Companies'},
        ),
    ]
