# Generated by Django 2.1 on 2018-12-11 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_verbose_name_companies'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_trial_available',
            field=models.BooleanField(default=True, verbose_name='is_trial_available'),
        ),
    ]
