# Generated by Django 2.1 on 2019-01-04 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_auto_20181210_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='fax',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='fax'),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='website'),
        ),
    ]
