# Generated by Django 2.1 on 2019-02-28 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0014_companyuser_candidates_statuses'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyActivityReport',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('company.company',),
        ),
        migrations.CreateModel(
            name='CompanyRegistrationReport',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('company.company',),
        ),
        migrations.CreateModel(
            name='CompanyTransactionsReport',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('company.company',),
        ),
    ]
