# Generated by Django 2.1 on 2018-11-19 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_purchaised_job_seekers'),
        ('candidate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('rating', models.CharField(choices=[('NO_RATING', 'No Rating'), ('POOR', 'Poor'), ('GOOD', 'Good'), ('VERY_GOOD', 'Very good'), ('EXCELLENT', 'Excellent')], default='NO_RATING', max_length=16, verbose_name='rating')),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='candidate.Candidate')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.CompanyUser')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
