# Generated by Django 2.1 on 2018-11-19 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0007_related_name_applies'),
        ('candidate', '0002_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='apply',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apply.Apply'),
        ),
    ]
