# Generated by Django 2.1 on 2018-11-28 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0004_auto_20181123_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='previous_applied_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='previous_applied_date'),
        ),
    ]
