# Generated by Django 2.1 on 2018-12-29 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0005_previous_applied_date_field'),
        ('leet', '0001_initial')
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='previous_status',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='previous status'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='leet.CandidateStatus'),
        ),
    ]
