# Generated by Django 2.1 on 2019-01-03 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leet', '0005_drop_null'),
        ('candidate', '0006_refactored_candidate_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_steps', to='candidate.Candidate')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leet.CandidateStatus')),
            ],
            options={
                'ordering': ('status__workflow_value',),
            },
        ),
    ]
