# Generated by Django 2.1 on 2019-01-11 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0007_workflowstep'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='candidate',
            unique_together=set(),
        ),
    ]
