# Generated by Django 2.1 on 2019-01-11 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0008_drop_candidate_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='apply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apply.Apply'),
        ),
    ]
