# Generated by Django 2.1 on 2019-01-14 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0009_apply_foreign_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='previous_status',
        ),
    ]
