# Generated by Django 2.1 on 2019-01-25 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0014_companyuser_candidates_statuses'),
        ('candidate', '0010_drop_previous_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowstep',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.CompanyUser'),
        ),
    ]
