# Generated by Django 2.1 on 2018-12-29 12:04

from django.db import migrations
from leet import constants


def load_statuses(apps, schema_editor):
    CandidateStatus = apps.get_model('leet', 'CandidateStatus')
    data = [{'name': i} for i in constants.CANDIDATE_STATUSES]
    CandidateStatus.objects.bulk_create(CandidateStatus(**i) for i in data)


class Migration(migrations.Migration):

    dependencies = [
        ('leet', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_statuses)
    ]
