# Generated by Django 2.1 on 2019-01-03 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leet', '0002_candidates_workflow_statuses_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatestatus',
            name='workflow_value',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='workflow_value'),
        ),
    ]
