# Generated by Django 2.1 on 2019-01-03 06:18

from django.db import migrations

from leet import constants


def load_steps(apps, schema_editor):
    CandidateStatus = apps.get_model('leet', 'CandidateStatus')
    statuses = CandidateStatus.objects.all()
    for status in statuses:
        status.workflow_value = constants.CANDIDATE_STATUS_WORKFLOW_VALUE[status.name]
        status.save()


class Migration(migrations.Migration):

    dependencies = [
        ('leet', '0003_candidatestatus_workflow_value'),
    ]

    operations = [
        migrations.RunPython(load_steps)
    ]
