# Generated by Django 2.1 on 2019-01-03 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leet', '0004_workflow_value_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatestatus',
            name='workflow_value',
            field=models.PositiveSmallIntegerField(verbose_name='workflow_value'),
        ),
    ]
