# Generated by Django 2.1 on 2019-02-20 10:44

from django.db import migrations

from leet import constants


def create_event_types(apps, schema_editor):
    model = apps.get_model('leet', 'EventType')
    data = [{
        'name': i
    } for i in constants.EVENT_TYPES]
    model.objects.bulk_create(model(**i) for i in data)


class Migration(migrations.Migration):

    dependencies = [
        ('leet', '0006_eventtype'),
    ]

    operations = [
        migrations.RunPython(create_event_types)
    ]
