# Generated by Django 2.1 on 2018-11-19 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('threadedcomments', '0003_threadedcomment_newest_activity'),
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobComment',
            fields=[
                ('threadedcomment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='threadedcomments.ThreadedComment')),
            ],
            options={
                'verbose_name': 'comment',
                'verbose_name_plural': 'comments',
                'ordering': ('submit_date',),
                'permissions': [('can_moderate', 'Can moderate comments')],
                'abstract': False,
            },
            bases=('threadedcomments.threadedcomment',),
        ),
    ]
