# Generated by Django 2.1 on 2018-12-12 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_jobcomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobcomment',
            options={'verbose_name': 'Job comment'},
        ),
        migrations.AlterModelOptions(
            name='jobseekercomment',
            options={'verbose_name': 'Job seeker comment'},
        ),
    ]
