# Generated by Django 2.1 on 2018-10-03 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('job_seeker', '0004_education'),
        ('job', '0004_owner_and_publsh_date_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('APPLIED', 'Applied'), ('NEED_REVIEW', 'Need review')], default='APPLIED', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Autoapply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=256)),
                ('status', models.CharField(choices=[('SAVED', 'Saved'), ('STARTED', 'Started')], default='SAVED', max_length=40)),
                ('query_params', models.CharField(blank=True, max_length=256)),
                ('number', models.IntegerField()),
                ('applied_jobs', models.ManyToManyField(through='apply.Apply', to='job.Job')),
                ('deleted_jobs', models.ManyToManyField(related_name='autoapply_dj', to='job.Job')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autoapplies', to='job_seeker.JobSeeker')),
                ('stopped_jobs', models.ManyToManyField(related_name='autoapply_sj', to='job.Job')),
            ],
        ),
        migrations.AddField(
            model_name='apply',
            name='autoapply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apply.Autoapply'),
        ),
        migrations.AddField(
            model_name='apply',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.Job'),
        ),
        migrations.AddField(
            model_name='apply',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_seeker.JobSeeker'),
        ),
        migrations.AlterUniqueTogether(
            name='autoapply',
            unique_together={('title', 'owner')},
        ),
        migrations.AlterUniqueTogether(
            name='apply',
            unique_together={('job', 'owner')},
        ),
    ]
