# Generated by Django 2.1 on 2018-10-19 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_seeker', '0007_relation_name_job_seeker'),
        ('job', '0007_jobs_views'),
        ('apply', '0002_related_name_applies'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autoapply',
            old_name='applied_jobs',
            new_name='jobs',
        ),
        migrations.AddField(
            model_name='apply',
            name='applied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='autoapply',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apply',
            name='autoapply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apply.Autoapply'),
        ),
        migrations.AlterField(
            model_name='apply',
            name='status',
            field=models.CharField(choices=[('APPLIED', 'Applied'), ('NEED_REVIEW', 'Need review'), ('VIEWED', 'Viewed'), ('NEW', 'New')], default='APPLIED', max_length=40),
        ),
        migrations.AlterField(
            model_name='autoapply',
            name='status',
            field=models.CharField(choices=[('SAVED', 'Saved'), ('IN_PROGRESS', 'In Progress'), ('FINISHED', 'Finished'), ('STOPPED', 'Stopped')], default='SAVED', max_length=40),
        ),
        migrations.AlterUniqueTogether(
            name='apply',
            unique_together={('job', 'owner', 'autoapply')},
        ),
    ]
