# Generated by Django 2.1 on 2018-10-25 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0003_auto_20181019_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='autoapply',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
