# Generated by Django 2.1 on 2018-11-08 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0004_auto_20181025_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoapply',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
