# Generated by Django 2.1 on 2018-11-13 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_seeker', '0013_add_cover_letter'),
        ('apply', '0005_autoapply_finished_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='cover_letter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='job_seeker.CoverLetter'),
        ),
    ]
