# Generated by Django 2.1 on 2018-11-13 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0006_apply_cover_letter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applies', to='job_seeker.JobSeeker'),
        ),
    ]
