# Generated by Django 2.1 on 2018-10-01 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='education_strict',
            field=models.BooleanField(default=False, verbose_name='education_strict'),
        ),
        migrations.AddField(
            model_name='job',
            name='publish_date',
            field=models.DateField(blank=True, null=True, verbose_name='publish_date'),
        ),
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('CLOSED', 'Closed'), ('DELAYED', 'Delayed')], default='DRAFT', max_length=16, verbose_name='status'),
        ),
    ]
