# Generated by Django 2.1 on 2018-10-08 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_companyadmin'),
        ('job', '0004_owner_and_publsh_date_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='company.CompanyAdmin'),
        ),
    ]
