# Generated by Django 2.1 on 2018-10-09 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_owner_company_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='travel',
            field=models.CharField(blank=True, choices=[('NO_TRAVEL', 'No Travel'), ('MINIMAL', 'Minimal'), ('TWENTY_FIVE_OR_LESS', '25% or Less'), ('FIFTY_OR_LESS', '50% or Less'), ('FIFTY_OR_MORE', '50% or More')], max_length=40, verbose_name='travel'),
        ),
    ]
