# Generated by Django 2.1 on 2018-10-11 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_seeker', '0006_travel_enums'),
        ('job', '0006_travel_enums'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='job.Job')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_seeker.JobSeeker')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
