# Generated by Django 2.1 on 2018-10-25 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_jobs_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
