# Generated by Django 2.1 on 2018-10-25 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_auto_20181025_0625'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='viewjob',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
