# Generated by Django 2.1 on 2018-11-12 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0009_auto_20181025_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_cover_letter_required',
            field=models.BooleanField(default=False),
        ),
    ]
