# Generated by Django 2.1 on 2018-12-03 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0010_job_is_cover_letter_required'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ('name',)},
        ),
    ]
