# Generated by Django 2.1 on 2018-11-28 12:53

from django.db import migrations, models
import django.db.models.deletion


def set_new_york_location_for_existing_jobs(apps, schema_editor):
    Country = apps.get_model('geo', 'Country')
    City = apps.get_model('geo', 'City')
    Address = apps.get_model('geo', 'Address')
    Job = apps.get_model('job', 'Job')
    usa_country = Country.objects.get(name='USA')
    ny_city = City.objects.get(
        name='New York', state__name='New York', state__country=usa_country)
    for job in Job.objects.all():
        job.location = Address.objects.create(country=usa_country, city=ny_city)
        job.save()


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0011_ordering_skills_by_name'),
        ('geo', '0008_null_country')
    ]

    operations = [
        migrations.RemoveField(model_name='job', name='location'),
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='geo.Address',
                                       blank=True, null=True),
        ),
        migrations.RunPython(set_new_york_location_for_existing_jobs),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='geo.Address'),
        ),

    ]
