# Generated by Django 2.1 on 2018-12-04 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0012_auto_20181128_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='closing_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
