# Generated by Django 2.1 on 2018-12-12 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0013_closing_date_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subindustry',
            options={'verbose_name_plural': 'Sub-industries'},
        ),
    ]
