# Generated by Django 2.1 on 2018-12-17 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0015_job_ban_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='industry',
            options={'verbose_name_plural': 'Industries'},
        ),
    ]
