# Generated by Django 2.1 on 2019-01-03 12:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0016_auto_20181217_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skill',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
