# Generated by Django 2.1 on 2019-01-04 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0017_auto_20190103_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='benefits',
            field=models.CharField(blank=True, choices=[('FULL_BENEFITS', 'Full Benefits'), ('PARTIAL_BENEFITS', 'Partial Benefits'), ('HEALTH', 'Health'), ('VISION', 'Vision'), ('HEALTH_AND_VISION', 'Health & Vision'), ('FOUR_OH_ONE_KEY', '401K')], max_length=40, null=True, verbose_name='benefits'),
        ),
        migrations.AlterField(
            model_name='job',
            name='clearance',
            field=models.CharField(blank=True, choices=[('SECRET', 'Secret'), ('TOP_SECRET', 'Top Secret'), ('TOP_SECRET_SCI', 'Top Secret/SCI'), ('MBI', 'MBI'), ('PUBLIC_TRUST', 'Public Trust'), ('CONFIDENTIAL', 'Confidential'), ('UNCLASSIFIED', 'Unclassified')], max_length=40, null=True, verbose_name='clearance'),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='job',
            name='education',
            field=models.CharField(blank=True, choices=[('HIGH_SCHOOL', 'High School'), ('CERTIFICATION', 'Certification'), ('ASSOCIATES_DEGREE', 'Associates Degree'), ('BACHELORS_DEGREE', "Bachelor's Degree"), ('MASTERS_DEGREE', "Master's Degree"), ('PHD', 'PHD')], max_length=40, null=True, verbose_name='education'),
        ),
        migrations.AlterField(
            model_name='job',
            name='experience',
            field=models.CharField(blank=True, choices=[('NO_EXPERIENCE', 'No experience'), ('LESS_THAN_1', 'Less than 1 year'), ('FROM_1_TO_2', '1 to 2 years'), ('FROM_3_TO_5', '3 to 5 years'), ('FROM_5_TO_10', '5 to 10 years'), ('MORE_THAN_10', '10+ years')], max_length=40, null=True, verbose_name='experience'),
        ),
        migrations.AlterField(
            model_name='job',
            name='position_type',
            field=models.CharField(blank=True, choices=[('FULL_TIME', 'Full Time'), ('PART_TIME', 'Part Time'), ('CONTRACT', 'Contract'), ('TEMPORARY', 'Temporary'), ('INTERNSHIP', 'Internship'), ('COMMISSION', 'Commission')], max_length=40, null=True, verbose_name='position_type'),
        ),
        migrations.AlterField(
            model_name='job',
            name='travel',
            field=models.CharField(blank=True, choices=[('NO_TRAVEL', 'No Travel'), ('MINIMAL', 'Minimal'), ('TWENTY_FIVE_OR_LESS', '25% or Less'), ('FIFTY_OR_LESS', '50% or Less'), ('FIFTY_OR_MORE', '50% or More')], max_length=40, null=True, verbose_name='travel'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
    ]
