# Generated by Django 2.1 on 2019-01-24 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0018_nullable_for_job_models'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subindustry',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='subindustry',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='job',
            name='subindustry',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='subindustries',
        ),
        migrations.AddField(
            model_name='skill',
            name='type',
            field=models.CharField(max_length=256, null=True, verbose_name='type'),
        ),
        migrations.DeleteModel(
            name='Subindustry',
        ),
    ]
