# Generated by Django 2.1 on 2019-01-24 14:51
import os

from django.db import migrations

from job.migrations.data import csv_reader


CURRENT_DIR_PATH = os.path.dirname(os.path.abspath(__file__))
SKILLS_CSV_DIR_PATH = os.path.join(CURRENT_DIR_PATH, 'data', 'skills')
INDUSTRIES_CSV_FILE = 'industries.csv'
INDUSTRIES_CSV_PATH = os.path.join(CURRENT_DIR_PATH, 'data', INDUSTRIES_CSV_FILE)


def load_all_skills(apps, schema_editor):
    Skill = apps.get_model('job', 'Skill')
    skills = {}
    for file in os.listdir(SKILLS_CSV_DIR_PATH):
        csv_path = os.path.join(SKILLS_CSV_DIR_PATH, file)
        skills.update(csv_reader.get_skills_from_csv(csv_path))

    Skill.objects.bulk_create(
        [Skill(
            name=key,
            description=value['description'],
            type=value['type']
        ) for key, value in skills.items()]
    )


def load_industries(apps, schema_editor):
    Industry = apps.get_model('job', 'Industry')
    industries = csv_reader.get_column_from_csv(csv_file_path=INDUSTRIES_CSV_PATH,
                                                column_name='name')
    Industry.objects.bulk_create(
        [Industry(
            name=industry_name,
        ) for industry_name in industries]
    )


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0019_auto_20190124_1446'),
    ]

    operations = [
        migrations.RunPython(load_all_skills),
        migrations.RunPython(load_industries),
    ]
