# Generated by Django 2.1 on 2019-02-22 10:38

import uuid

from django.db import migrations, models


def set_guids(apps, schema_editor):
    Job = apps.get_model("job", "Job")
    jobs = Job.objects.all()
    for job in jobs:
        job.guid = uuid.uuid4()
        job.save()


class Migration(migrations.Migration):
    dependencies = [
        ('job', '0020_load_skills_industries'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='guid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=False),
        ),
        migrations.RunPython(set_guids),
    ]
