# Generated by Django 2.1 on 2019-02-22 11:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0021_job_guid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='guid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
