# Generated by Django 2.1 on 2019-03-06 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_seeker', '0030_jobseekeractivityreport_jobseekerregistrationreport'),
        ('job', '0022_auto_20190222_1157'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('criteria', models.TextField()),
                ('is_saved', models.BooleanField(default=False)),
                ('count', models.PositiveIntegerField(default=1)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='searches', to='job_seeker.JobSeeker')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
