# Generated by Django 2.1 on 2019-03-11 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0024_auto_20190311_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(max_length=1024, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='job',
            name='position_type',
            field=models.CharField(choices=[('FULL_TIME', 'Full Time'), ('PART_TIME', 'Part Time'), ('CONTRACT', 'Contract'), ('TEMPORARY', 'Temporary'), ('INTERNSHIP', 'Internship'), ('COMMISSION', 'Commission')], max_length=40, verbose_name='position_type'),
        ),
    ]
