# Generated by Django 2.1 on 2019-03-21 07:53

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations
from job import search_vectors


def update_job_documents(apps, schema_editor):
    Job = apps.get_model("job", "Job")
    jobs = Job.objects.annotate(
        document=search_vectors.SEARCH_VECTOR,
        location_document=search_vectors.LOCATION_SEARCH_VECTOR,
    )
    for job in jobs:
        job.search_vector = job.document
        job.location_search_vector = job.location_document
        job.save(update_fields=['search_vector', 'location_search_vector'])


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0026_auto_20190313_0754'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='location_search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='job',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='job_job_search__ad23b1_gin'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=django.contrib.postgres.indexes.GinIndex(fields=['location_search_vector'], name='job_job_locatio_18f35f_gin'),
        ),
        migrations.RunPython(update_job_documents)
    ]
