# Generated by Django 2.1 on 2019-07-15 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0027_auto_20190321_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='clearance',
            field=models.CharField(blank=True, choices=[('SECRET', 'Secret'), ('TOP_SECRET', 'Top Secret'), ('TOP_SECRET_SCI', 'Top Secret/SCI'), ('MBI', 'MBI'), ('PUBLIC_TRUST', 'Public Trust'), ('CONFIDENTIAL', 'Confidential'), ('UNCLASSIFIED', 'Unclassified'), ('', 'No selection')], default='', max_length=40, verbose_name='clearance'),
            preserve_default=False,
        ),
    ]
