# Generated by Django 2.1 on 2019-08-01 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0028_auto_20190715_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='benefits',
            field=models.CharField(choices=[('FULL_BENEFITS', 'Full Benefits'), ('PARTIAL_BENEFITS', 'Partial Benefits'), ('HEALTH', 'Health'), ('VISION', 'Vision'), ('HEALTH_AND_VISION', 'Health & Vision'), ('FOUR_OH_ONE_KEY', '401K'), ('NO_BENEFITS', 'No Benefits')], default='NO_BENEFITS', max_length=40, verbose_name='benefits'),
        ),
        migrations.AlterField(
            model_name='job',
            name='clearance',
            field=models.CharField(choices=[('SECRET', 'Secret'), ('TOP_SECRET', 'Top Secret'), ('TOP_SECRET_SCI', 'Top Secret/SCI'), ('MBI', 'MBI'), ('PUBLIC_TRUST', 'Public Trust'), ('CONFIDENTIAL', 'Confidential'), ('UNCLASSIFIED', 'Unclassified'), ('NO_CLEARANCE', 'No Clearance')], default='NO_CLEARANCE', max_length=40, verbose_name='clearance'),
        ),
        migrations.AlterField(
            model_name='job',
            name='education',
            field=models.CharField(blank=True, choices=[('HIGH_SCHOOL', 'High School'), ('CERTIFICATION', 'Certification'), ('ASSOCIATES_DEGREE', 'Associates Degree'), ('BACHELORS_DEGREE', "Bachelor's Degree"), ('MASTERS_DEGREE', "Master's Degree"), ('PHD', 'PHD'), ('NO_EDUCATION', 'No Education')], default='NO_EDUCATION', max_length=40, verbose_name='education'),
        ),
        migrations.AlterField(
            model_name='job',
            name='experience',
            field=models.CharField(choices=[('NO_EXPERIENCE', 'No experience'), ('LESS_THAN_1', 'Less than 1 year'), ('FROM_1_TO_2', '1 to 2 years'), ('FROM_3_TO_5', '3 to 5 years'), ('FROM_5_TO_10', '5 to 10 years'), ('MORE_THAN_10', '10+ years')], default='NO_EXPERIENCE', max_length=40, verbose_name='experience'),
        ),
        migrations.AlterField(
            model_name='job',
            name='travel',
            field=models.CharField(choices=[('NO_TRAVEL', 'No Travel'), ('MINIMAL', 'Minimal'), ('TWENTY_FIVE_OR_LESS', '25% or Less'), ('FIFTY_OR_LESS', '50% or Less'), ('FIFTY_OR_MORE', '50% or More')], default='NO_TRAVEL', max_length=40, verbose_name='travel'),
        ),
    ]
