# Generated by Django 2.1 on 2019-09-04 10:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0030_auto_20190802_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='autoapply_minimal_percent',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
    ]
