# Generated by Django 2.1 on 2019-09-05 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0031_job_autoapply_minimal_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='manual_apply_strict_required_skills_matching',
            field=models.BooleanField(default=False),
        ),
    ]
