# Generated by Django 2.1 on 2019-09-11 10:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0032_job_manual_apply_strict_required_skills_matching'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='autoapply_minimal_percent',
            field=models.PositiveSmallIntegerField(default=100, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
    ]
