# Generated by Django 2.1 on 2018-10-15 09:16

from django.db import migrations
from survey import constants


def add_default_questions(apps, schema_editor):
    Question = apps.get_model('survey', 'Question')
    data = []
    for i in constants.DEFAULT_QUESTIONS:
        data.append({
            'body': i,
            'is_default': True
        })
    Question.objects.bulk_create(Question(**i) for i in data)


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            add_default_questions,
        )
    ]
