# Generated by Django 2.1 on 2018-10-23 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_jobs_views'),
        ('survey', '0002_default_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='job.Job'),
        ),
    ]
