# Generated by Django 2.1 on 2018-10-23 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_job_questions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answerjobseeker',
            old_name='job_seeker',
            new_name='owner',
        ),
    ]
