# Generated by Django 2.1 on 2018-10-25 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_jobs_views'),
        ('job_seeker', '0008_employment_field'),
        ('survey', '0004_owner_field_instead_job_seeker'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='answerjobseeker',
            unique_together={('job', 'owner', 'question')},
        ),
    ]
