# Generated by Django 2.1 on 2018-10-26 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_unique_job_owner_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='answerjobseeker',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='question',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
