# Generated by Django 2.1 on 2019-01-04 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0007_related_name_job_seeker_answers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='plain_text_value',
            field=models.TextField(blank=True, null=True, verbose_name='plain_text_value'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='yes_no_value',
            field=models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No')], max_length=8, null=True, verbose_name='yes_no_value'),
        ),
        migrations.AlterField(
            model_name='question',
            name='disqualifying_answer',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='disqualifying_answer'),
        ),
    ]
