# Generated by Django 2.1 on 2018-12-11 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0008_purchaised_job_seekers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('stripe_id', models.CharField(max_length=255, unique=True, verbose_name='stripe_id')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='company.Company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('stripe_id', models.CharField(max_length=255, unique=True, verbose_name='stripe_id')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('job_seekers_count', models.IntegerField(verbose_name='job_seekers_count')),
                ('jobs_count', models.IntegerField(verbose_name='jobs_count')),
                ('is_custom', models.BooleanField(default=False, verbose_name='is_custom')),
                ('price', models.IntegerField(verbose_name='price')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subscription.Customer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('stripe_id', models.CharField(max_length=255, unique=True, verbose_name='stripe_id')),
                ('is_trial', models.BooleanField(default=False, verbose_name='is_trial')),
                ('date_end', models.DateTimeField(verbose_name='date_end')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='subscription.Customer')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subscription.Plan')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
