# Generated by Django 2.1 on 2018-12-13 07:17

from django.db import migrations, models
import django.db.models.deletion


def set_customers_balance(apps, schema_editor):
    Balance = apps.get_model('subscription', 'Balance')
    Customer = apps.get_model('subscription', 'Customer')
    for customer in Customer.objects.all():
        customer.balance = Balance.objects.create()
        customer.save()


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_auto_20181212_1340'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('job_seekers_count', models.IntegerField(default=0, verbose_name='job_seekers_count')),
                ('jobs_count', models.IntegerField(default=0, verbose_name='jobs_count')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='balance',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='subscription.Balance'),
        ),
        migrations.RunPython(set_customers_balance),
        migrations.AlterField(
            model_name='customer',
            name='balance',
            field=models.OneToOneField(null=False, on_delete=django.db.models.deletion.CASCADE,
                                       to='subscription.Balance'))
    ]
