# Generated by Django 2.1 on 2018-12-21 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0005_auto_20181218_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='next_subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscription.Subscription'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('SCHEDULED', 'Scheduled')], default='DRAFT', max_length=40, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='subscription.Customer'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='date_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date_end'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='date_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date_start'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company.CompanyUser'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscription.Plan'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='stripe_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='stripe_id'),
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='next_plan',
        ),
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together={('customer', 'status')},
        ),
    ]
