# Generated by Django 2.1 on 2018-12-26 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0006_auto_20181221_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_payment_source_provided',
            field=models.BooleanField(default=False, verbose_name='is_payment_source_provided'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('DRAFT', 'Draft'), ('SCHEDULED', 'Scheduled')], default='DRAFT', max_length=40, verbose_name='status'),
        ),
    ]
