# Generated by Django 2.1 on 2018-12-27 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0007_auto_20181226_1957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balance',
            name='job_seekers_count',
        ),
        migrations.RemoveField(
            model_name='balance',
            name='jobs_count',
        ),
        migrations.AddField(
            model_name='balance',
            name='job_seekers_remain',
            field=models.IntegerField(default=0, verbose_name='job_seekers_remain'),
        ),
        migrations.AddField(
            model_name='balance',
            name='job_seekers_total',
            field=models.IntegerField(default=0, verbose_name='job_seekers_total'),
        ),
        migrations.AddField(
            model_name='balance',
            name='jobs_remain',
            field=models.IntegerField(default=0, verbose_name='jobs_remain'),
        ),
        migrations.AddField(
            model_name='balance',
            name='jobs_total',
            field=models.IntegerField(default=0, verbose_name='jobs_total'),
        ),
    ]
