# Generated by Django 2.1 on 2019-01-04 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0010_auto_20181228_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='stripe_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='stripe_id'),
        ),
    ]
