# Generated by Django 2.1 on 2019-01-11 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0013_companyuser_is_disabled_by_subscription'),
        ('subscription', '0011_nullable_for_subscription_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='customer',
        ),
        migrations.AddField(
            model_name='plan',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.Company'),
        ),
        migrations.AlterField(
            model_name='balance',
            name='job_seekers_remain',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='balance',
            name='job_seekers_total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='balance',
            name='jobs_remain',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='balance',
            name='jobs_total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='plan',
            name='is_custom',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='plan',
            name='job_seekers_count',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='plan',
            name='jobs_count',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='plan',
            name='price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='date_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='date_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='is_auto_renew',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='is_trial',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('DRAFT', 'Draft'), ('SCHEDULED', 'Scheduled')], default='DRAFT', max_length=40),
        ),
    ]
