# Generated by Django 2.1 on 2019-02-06 10:30

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0012_auto_20190111_0549'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='plan',
            managers=[
                ('admin_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='plan',
            name='deletion_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='new_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='price_modified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
