# Generated by Django 2.1 on 2019-02-12 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0013_auto_20190206_1030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='price_modified_at',
            new_name='price_apply_date',
        ),
    ]
