# Generated by Django 2.1 on 2019-02-28 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0014_auto_20190212_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='new_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
