# Generated by Django 2.1 on 2019-03-01 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0015_auto_20190228_0643'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('stripe_id', models.CharField(max_length=255, unique=True, verbose_name='stripe_id')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('datetime_of_payment', models.DateTimeField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='subscription.Customer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
