# Generated by Django 2.1 on 2019-03-28 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0017_invoice_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.CompanyUser'),
        ),
    ]
