# Generated by Django 2.1 on 2019-09-23 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0018_auto_20190328_0625'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='is_reporting_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
