# Generated by Django 2.1 on 2019-02-13 11:00

from django.db import migrations

from leet import constants


def create_categories(apps, schema_editor):
    model = apps.get_model('letter_template', 'TemplateCategory')
    data = [{
        'name': i
    } for i in constants.EVENT_TYPES]
    model.objects.bulk_create(model(**i) for i in data)


class Migration(migrations.Migration):

    dependencies = [
        ('letter_template', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_categories)
    ]
