# Generated by Django 2.1 on 2019-02-20 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leet', '0006_eventtype'),
        ('letter_template', '0002_template_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lettertemplate',
            name='category',
        ),
        migrations.AddField(
            model_name='lettertemplate',
            name='event_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='leet.EventType'),
        ),
        migrations.DeleteModel(
            name='TemplateCategory',
        ),
    ]
