# Generated by Django 2.1 on 2018-10-26 10:46

from django.db import migrations

from permission import constants


def create_permissions_group(apps, schema_editor):
    PermissionGroup = apps.get_model('permission', 'PermissionGroup')
    for i in constants.PERMISSION_GROUPS:
        PermissionGroup.objects.create(**i)


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_permissions_group)
    ]
