# Generated by Django 2.1 on 2018-10-26 11:57

from django.db import migrations
from django.contrib.auth import models

from permission import constants
from permission import utils


def add_company_user_user_permissions(apps, schema_editor):
    perms = (
        utils.get_permission_object(
            apps,
            'job',
            'Job',
            constants.Permissions.view_job.value),
        utils.get_permission_object(
            apps,
            'job',
            'Job',
            constants.Permissions.restore_job.value),
        utils.get_permission_object(
            apps,
            'company',
            'Company',
            constants.Permissions.view_company.value),
        utils.get_permission_object(
            apps,
            'company',
            'Company',
            constants.Permissions.change_company_logo.value),
        utils.get_permission_object(
            apps,
            'survey',
            'Question',
            constants.Permissions.add_question.value),
        utils.get_permission_object(
            apps,
            'survey',
            'Question',
            constants.Permissions.view_question.value),
        utils.get_permission_object(
            apps,
            'survey',
            'Question',
            constants.Permissions.change_question.value),
        utils.get_permission_object(
            apps,
            'survey',
            'Question',
            constants.Permissions.delete_question.value),
        utils.get_permission_object(
            apps,
            'survey',
            'Survey',
            constants.Permissions.add_survey.value),
        utils.get_permission_object(
            apps,
            'survey',
            'Survey',
            constants.Permissions.view_survey.value),
        utils.get_permission_object(
            apps,
            'survey',
            'Survey',
            constants.Permissions.change_survey.value),
        utils.get_permission_object(
            apps,
            'survey',
            'Survey',
            constants.Permissions.delete_survey.value),
        utils.get_permission_object(
            apps,
            'survey',
            'AnswerJobSeeker',
            constants.Permissions.view_answerjobseeker.value),
        utils.get_permission_object(
            apps,
            'job',
            'Job',
            constants.Permissions.view_job_candidates.value),
        utils.get_permission_object(
            apps,
            'job_seeker',
            'JobSeeker',
            constants.Permissions.view_jobseeker.value),
        utils.get_permission_object(
            apps,
            'job',
            'ViewJob',
            constants.Permissions.view_viewjob.value),
        utils.get_permission_object(
            apps,
            'job_seeker',
            'JobExperience',
            constants.Permissions.view_jobexperience.value),
        utils.get_permission_object(
            apps,
            'job_seeker',
            'Education',
            constants.Permissions.view_education.value),
        utils.get_permission_object(
            apps,
            'job_seeker',
            'Certification',
            constants.Permissions.view_certification.value),
    )

    company_admin = models.Group.objects.get(name='company_admin')
    company_admin.permissions.add(*perms)


class Migration(migrations.Migration):

    dependencies = [
        (
            'permission', '0002_permission_group_data',
        ),
        (
            'survey', '0001_initial'
        )
    ]

    operations = [
        migrations.RunPython(add_company_user_user_permissions)
    ]
