# Generated by Django 2.1 on 2018-10-26 14:49

from django.db import migrations

from django.contrib.auth import models

from permission import constants
from permission import utils


def add_perms_to_job_seeker(apps, schema_editor):
    perms = (
        utils.get_permission_object(
            apps,
            'job',
            'Job',
            constants.Permissions.view_job.value),
        utils.get_permission_object(
            apps,
            'survey',
            'AnswerJobSeeker',
            constants.Permissions.view_answerjobseeker.value),
        utils.get_permission_object(
            apps,
            'survey',
            'AnswerJobSeeker',
            constants.Permissions.add_answerjobseeker.value),
        utils.get_permission_object(
            apps,
            'job_seeker',
            'SavedJob',
            constants.Permissions.add_savedjob.value),
        utils.get_permission_object(
            apps,
            'job_seeker',
            'SavedJob',
            constants.Permissions.view_savedjob.value),
        utils.get_permission_object(
            apps,
            'job_seeker',
            'JobSeeker',
            constants.Permissions.upload_photo.value),
        utils.get_permission_object(
            apps,
            'job_seeker',
            'JobExperience',
            constants.Permissions.add_jobexperience.value),
        utils.get_permission_object(
            apps,
            'job_seeker',
            'JobExperience',
            constants.Permissions.view_jobexperience.value),
        utils.get_permission_object(
            apps,
            'job_seeker',
            'JobExperience',
            constants.Permissions.change_jobexperience.value),
        utils.get_permission_object(
            apps,
            'job_seeker',
            'JobExperience',
            constants.Permissions.delete_jobexperience.value),
        utils.get_permission_object(
            apps,
            'job_seeker',
            'JobSeeker',
            constants.Permissions.view_jobseeker.value),
        utils.get_permission_object(
            apps,
            'job_seeker',
            'JobSeeker',
            constants.Permissions.change_jobseeker.value),
        utils.get_permission_object(
            apps,
            'job_seeker',
            'Education',
            constants.Permissions.add_education.value),
        utils.get_permission_object(
            apps,
            'job_seeker',
            'Education',
            constants.Permissions.view_education.value),
        utils.get_permission_object(
            apps,
            'job_seeker',
            'Education',
            constants.Permissions.change_education.value),
        utils.get_permission_object(
            apps,
            'job_seeker',
            'Education',
            constants.Permissions.delete_education.value),
        utils.get_permission_object(
            apps,
            'job_seeker',
            'Certification',
            constants.Permissions.add_certification.value),
        utils.get_permission_object(
            apps,
            'job_seeker',
            'Certification',
            constants.Permissions.view_certification.value),
        utils.get_permission_object(
            apps,
            'job_seeker',
            'Certification',
            constants.Permissions.change_certification.value),
        utils.get_permission_object(
            apps,
            'job_seeker',
            'Certification',
            constants.Permissions.delete_certification.value),
        utils.get_permission_object(
            apps,
            'apply',
            'AutoApply',
            constants.Permissions.view_autoapply_jobs.value),
        utils.get_permission_object(
            apps,
            'apply',
            'AutoApply',
            constants.Permissions.view_autoapply_job_detail.value),
        utils.get_permission_object(
            apps,
            'apply',
            'Autoapply',
            constants.Permissions.add_autoapply.value),
        utils.get_permission_object(
            apps,
            'apply',
            'Autoapply',
            constants.Permissions.view_autoapply.value),
        utils.get_permission_object(
            apps,
            'apply',
            'Autoapply',
            constants.Permissions.change_autoapply.value),
        utils.get_permission_object(
            apps,
            'apply',
            'Autoapply',
            constants.Permissions.delete_autoapply.value),
        utils.get_permission_object(
            apps,
            'apply',
            'Autoapply',
            constants.Permissions.start_autoapply.value),
        utils.get_permission_object(
            apps,
            'apply',
            'Autoapply',
            constants.Permissions.stop_autoapply.value),
        utils.get_permission_object(
            apps,
            'apply',
            'Autoapply',
            constants.Permissions.restart_autoapply.value),
        utils.get_permission_object(
            apps,
            'apply',
            'Autoapply',
            constants.Permissions.autoapply_to_job.value),
        utils.get_permission_object(
            apps,
            'apply',
            'Autoapply',
            constants.Permissions.view_applied_jobs.value),
        utils.get_permission_object(
            apps,
            'apply',
            'Apply',
            constants.Permissions.view_applied_jobs.value),
        utils.get_permission_object(
            apps,
            'apply',
            'Apply',
            constants.Permissions.add_apply.value),
    )

    job_seeker = models.Group.objects.get(name='job_seeker')
    job_seeker.permissions.add(*perms)


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0003_company_admin_permissions'),
    ]

    operations = [
        migrations.RunPython(add_perms_to_job_seeker)
    ]
