# Generated by Django 2.1 on 2018-10-30 12:48

from django.db import migrations

from permission import constants
from permission import utils
from permission import models


def grouped_perms(group_name, perms):
    group = models.PermissionGroup.objects.get(name=group_name)
    group.permissions.add(*perms)
    group.save()


def get_manage_users_perms(apps):
    return (
        utils.get_permission_object(
            apps,
            'company',
            'CompanyAdmin',
            ('add_companyadmin', 'Can add company admin')),
        utils.get_permission_object(
            apps,
            'company',
            'CompanyAdmin',
            ('change_companyadmin', 'Can change company admin')),
        utils.get_permission_object(
            apps,
            'company',
            'CompanyAdmin',
            ('view_companyadmin', 'Can view company admin')),
        utils.get_permission_object(
            apps,
            'company',
            'CompanyAdmin',
            ('delete_companyadmin', 'Can delete company admin')),
    )


def get_manage_job_posting_perms(apps):
    return (
        utils.get_permission_object(
            apps,
            'job',
            'Job',
            constants.Permissions.add_job.value),
        utils.get_permission_object(
            apps,
            'job',
            'Job',
            constants.Permissions.change_job.value),
        utils.get_permission_object(
            apps,
            'job',
            'Job',
            constants.Permissions.delete_job.value),
    )


def get_company_perms(apps):
    return (
        utils.get_permission_object(
            apps,
            'company',
            'Company',
            constants.Permissions.change_company.value),
    )


def get_purchase_js_profile_perms(apps):
    return (
        utils.get_permission_object(
            apps,
            'job_seeker',
            'JobSeeker',
            constants.Permissions.purchase_js_profile.value),
    )


def grouped_company_users_perms(apps, schema_editor):

    grouped_perms(
        constants.MANAGE_COMPANY_USERS_GROUP,
        get_manage_users_perms(apps)
    )
    grouped_perms(
        constants.MANAGE_JOB_POSTINGS_GROUP,
        get_manage_job_posting_perms(apps)
    )
    grouped_perms(
        constants.EDIT_COMPANY_PROFILE_GROUP,
        get_company_perms(apps)
    )
    grouped_perms(
        constants.PURCHASE_JSPROFILE_GROUP,
        get_purchase_js_profile_perms(apps)
    )


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0004_job_seeker_all_perms'),
    ]

    operations = [
        migrations.RunPython(grouped_company_users_perms)
    ]
