# Generated by Django 2.1 on 2018-11-02 07:57

from django.db import migrations
from django.contrib.auth import models

from permission import constants
from permission import utils


def add_permissions(apps, schema_editor):
    perm = utils.get_permission_object(
        apps,
        'permission',
        'PermissionGroup',
        constants.Permissions.view_permissiongroup.value
    )
    company_user = models.Group.objects.get(name='company_admin')
    company_user.permissions.add(perm)


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0005_grouped_permissions_data'),
    ]

    operations = [
        migrations.RunPython(add_permissions)
    ]
