# Generated by Django 2.1 on 2018-11-09 11:12

from django.contrib.auth import models
from django.db import migrations

from permission import constants, utils


def add_permissions(apps, schema_editor):
    perm = utils.get_permission_object(
        apps,
        'job_seeker',
        'JobSeeker',
        constants.Permissions.is_job_seeker.value
    )
    job_seeker = models.Group.objects.get_by_natural_key('job_seeker')
    job_seeker.permissions.add(perm)

    perm = utils.get_permission_object(
        apps,
        'company',
        'CompanyAdmin',
        constants.Permissions.is_company_user.value
    )
    company_admin = models.Group.objects.get_by_natural_key('company_admin')
    company_admin.permissions.add(perm)


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0006_view_grouped_permissions'),
    ]

    operations = [
        migrations.RunPython(add_permissions)
    ]
