# Generated by Django 2.1 on 2018-11-08 18:04

from django.db import migrations

from permission import utils
from permission import constants
from permission import models


def add_company_user_permissions(apps, schema_editor):
    perms = (
        utils.get_permission_object(
            apps,
            'company',
            'CompanyUser',
            constants.Permissions.add_companyuser.value),
        utils.get_permission_object(
            apps,
            'company',
            'CompanyUser',
            constants.Permissions.change_companyuser.value),
        utils.get_permission_object(
            apps,
            'company',
            'CompanyUser',
            constants.Permissions.view_companyuser.value),
        utils.get_permission_object(
            apps,
            'company',
            'CompanyUser',
            constants.Permissions.delete_companyuser.value),
    )
    group = models.PermissionGroup.objects.get_by_natural_key(
        constants.MANAGE_COMPANY_USERS_GROUP)
    group.permissions.clear()
    group.permissions.add(*perms)
    group.save()


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0008_export_job_csv_permissions'),
    ]

    operations = [
        migrations.RunPython(add_company_user_permissions)
    ]
