# Generated by Django 2.1 on 2018-11-14 05:37

from django.db import migrations
from django.contrib.auth import models

from permission import constants
from permission import utils


def add_permissions(apps, schema_editor):
    perm = utils.get_permission_object(
        apps,
        'job_seeker',
        'JobSeeker',
        constants.Permissions.view_purchased_job_seekers.value
    )
    company_user = models.Group.objects.get_by_natural_key('company_user')
    company_user.permissions.add(perm)


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0010_cover_letter_permissions'),
    ]

    operations = [
        migrations.RunPython(add_permissions)
    ]
