# Generated by Django 2.1 on 2018-11-28 12:48

from django.db import migrations

from permission import utils
from permission import constants
from permission import models


def add_permissions(apps, schema_editor):
    perms = (
        utils.get_permission_object(
            apps,
            'candidate',
            'Candidate',
            constants.Permissions.restore_candidate.value),
    )
    group = models.PermissionGroup.objects.get_by_natural_key(
        constants.MANAGE_JOB_POSTINGS_GROUP)
    group.permissions.add(*perms)
    group.save()


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0016_manage_candidate_status_permissions'),
    ]

    operations = [
        migrations.RunPython(add_permissions)
    ]
