# Generated by Django 2.1 on 2018-11-27 10:30

from django.contrib.auth import models
from django.db import migrations

from permission import constants
from permission import utils


def add_permissions(apps, schema_editor):
    perm = (
        utils.get_permission_object(
            apps,
            'apply',
            'Apply',
            constants.Permissions.do_reapply.value)
    )
    job_seeker = models.Group.objects.get_by_natural_key('job_seeker')
    job_seeker.permissions.add(perm)


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0017_restore_candidate_permission'),
    ]

    operations = [
        migrations.RunPython(add_permissions)
    ]
