# Generated by Django 2.1 on 2018-12-11 12:30

from django.contrib.auth import models
from django.db import migrations

from permission import constants
from permission import utils


def add_permissions(apps, schema_editor):
    perm = (
        utils.get_permission_object(
            apps,
            'subscription',
            'Subscription',
            constants.Permissions.purchase_subscription.value)
    )
    subscription_manager = models.Group.objects.get_by_natural_key(
        constants.MANAGE_SUBSCRIPTION_PLAN_GROUP
    )
    subscription_manager.permissions.add(perm)


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0018_reapply_permissions'),
    ]

    operations = [
        migrations.RunPython(add_permissions)
    ]
