# Generated by Django 2.1 on 2018-12-29 12:30

from django.contrib.auth import models
from django.db import migrations

from permission import constants
from permission import utils


def add_permissions(apps, schema_editor):
    perm = (
        utils.get_permission_object(
            apps,
            'subscription',
            'Subscription',
            constants.Permissions.view_active_subscription.value)
    )
    company_user = models.Group.objects.get_by_natural_key('company_user')
    company_user.permissions.add(perm)


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0019_subscription_permissions'),
    ]

    operations = [
        migrations.RunPython(add_permissions)
    ]
