# Generated by Django 2.1 on 2018-12-29 22:29

from django.db import migrations

from permission import utils
from permission import constants


def add_permissions(apps, schema_editor):
    perm = (
        utils.get_permission_object(
            apps,
            'candidate',
            'Candidate',
            ('change_candidate_status', 'Can change candidate status'))
    )
    perm.codename = constants.Permissions.change_candidatestatus.value[0]
    perm.save()


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0020_active_subscription_permissions'),
    ]

    operations = [
        migrations.RunPython(add_permissions)
    ]
