# Generated by Django 2.1 on 2019-01-08 13:24

from django.db import migrations

from permission import constants
from permission import models
from permission import utils


def add_permissions(apps, schema_editor):
    perms = (
        utils.get_permission_object(
            apps,
            'job',
            'Job',
            constants.Permissions.set_job_closing_date.value),
        utils.get_permission_object(
            apps,
            'job',
            'Job',
            constants.Permissions.set_job_is_cover_letter_required.value),
        utils.get_permission_object(
            apps,
            'job',
            'Job',
            constants.Permissions.create_delayed_job.value),
    )
    group = models.PermissionGroup.objects.get_by_natural_key(
        constants.MANAGE_JOB_POSTINGS_GROUP)
    group.permissions.add(*perms)
    group.save()


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0021_refactoring_change_statusPermissions'),
    ]

    operations = [
        migrations.RunPython(add_permissions)
    ]
