# Generated by Django 2.1 on 2019-01-15 09:10
from django.db import migrations
from django.contrib.auth import models

from leet import enums
from permission import constants
from permission import utils


def add_permissions(apps, schema_editor):
    perm = utils.get_permission_object(
        apps,
        'company',
        'CompanyUser',
        constants.Permissions.change_viewed_candidate_statuses.value
    )
    company_user = models.Group.objects.get_by_natural_key(
        enums.AuthGroupsEnum.COMPANY_USER.value
    )
    company_user.permissions.add(perm)


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0026_manage_report_permissions'),
    ]

    operations = [
        migrations.RunPython(add_permissions)
    ]
