# Generated by Django 2.1 on 2019-01-23 12:03

from django.contrib.auth import models as auth_models
from django.db import migrations

from leet import enums
from permission import utils
from permission import constants
from permission import models


def add_permissions(apps, schema_editor):
    perm = (
        utils.get_permission_object(
            apps,
            'log',
            'Log',
            constants.Permissions.view_log.value)
    )
    company_user = auth_models.Group.objects.get_by_natural_key(
        enums.AuthGroupsEnum.COMPANY_USER.value
    )
    company_user.permissions.add(perm)
    company_user.save()
    perm = (
        utils.get_permission_object(
            apps,
            'log',
            'Log',
            constants.Permissions.delete_log.value)
    )
    group = models.PermissionGroup.objects.get_by_natural_key(
        constants.DELETE_LOG_GROUP)
    group.permissions.add(perm)
    group.save()


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0028_candidates_activities_permissions'),
        ('log', '0001_initial')
    ]

    operations = [
        migrations.RunPython(add_permissions)
    ]
