# Generated by Django 2.1 on 2019-02-19 08:40

from django.contrib.auth import models
from django.db import migrations

from permission import constants
from permission import utils


def add_permissions(apps, schema_editor):
    perm = utils.get_permission_object(
        apps,
        'company',
        'Company',
        constants.Permissions.change_company_logo.value
    )
    edit_company_group = models.Group.objects.get_by_natural_key(
        constants.EDIT_COMPANY_PROFILE_GROUP
    )
    edit_company_group.permissions.add(perm)
    company_user = models.Group.objects.get(name='company_user')
    company_user.permissions.remove(perm)


class Migration(migrations.Migration):
    dependencies = [
        ('permission', '0034_letter_template_permissions'),
    ]

    operations = [
        migrations.RunPython(add_permissions)
    ]
