# Generated by Django 2.1 on 2019-02-25 09:24

from django.db import migrations

from permission import constants


def create_permissions_group(apps, schema_editor):
    model = apps.get_model('permission', 'PermissionGroup')
    for i in constants.PERMISSION_GROUPS[-2:]:
        model.objects.get_or_create(**i)


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0038_view_company_users_candidates_jobs_enums_permissions'),
    ]

    operations = [
        migrations.RunPython(create_permissions_group)
    ]
