# Generated by Django 2.1 on 2019-02-25 07:43

from django.contrib.auth import models
from django.db import migrations

from leet import enums
from permission import constants
from permission import utils


def add_manage_event_permissions(apps, schema_editor):
    perms = (
        utils.get_permission_object(
            apps,
            'event',
            'Event',
            constants.Permissions.add_event.value),
        utils.get_permission_object(
            apps,
            'event',
            'Event',
            constants.Permissions.change_event.value),
        utils.get_permission_object(
            apps,
            'event',
            'Event',
            constants.Permissions.delete_event.value),
    )
    group = models.Group.objects.get_by_natural_key(
        constants.MANAGE_CALENDAR_EVENT_GROUP
    )
    group.permissions.add(*perms)


def add_create_event_permissions(apps, schema_editor):
    perms = (
        utils.get_permission_object(
            apps,
            'event',
            'Event',
            constants.Permissions.add_event.value),
    )
    group = models.Group.objects.get_by_natural_key(
        constants.CREATE_CALENDAR_EVENT_GROUP
    )
    group.permissions.add(*perms)


def add_company_user_event_permissions(apps, schema_editor):
    perms = (
        utils.get_permission_object(
            apps,
            'event',
            'Event',
            constants.Permissions.view_event.value),
    )
    company_user = models.Group.objects.get_by_natural_key(
        enums.AuthGroupsEnum.COMPANY_USER.value
    )
    company_user.permissions.add(*perms)


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0039_calendar_events_permission_group'),
    ]

    operations = [
        migrations.RunPython(add_manage_event_permissions),
        migrations.RunPython(add_create_event_permissions),
        migrations.RunPython(add_company_user_event_permissions),
    ]
