# Generated by Django 2.1 on 2018-10-26 14:49

from django.contrib.auth import models
from django.db import migrations

from leet import enums
from permission import constants
from permission import utils


def add_perms_to_job_seeker(apps, schema_editor):
    perms = (
        utils.get_permission_object(
            apps,
            'job',
            'Job',
            constants.Permissions.share_job.value),
    )

    company_user = models.Group.objects.get_by_natural_key(
        enums.AuthGroupsEnum.COMPANY_USER.value)
    company_user.permissions.add(*perms)


class Migration(migrations.Migration):
    dependencies = [
        ('permission', '0042_view_letter_template_permission'),
    ]

    operations = [
        migrations.RunPython(add_perms_to_job_seeker)
    ]
