# Generated by Django 2.1 on 2019-09-10 12:03

from django.db import migrations

from django.contrib.auth import models

from permission import constants
from permission import utils


def add_perms_to_job_seeker(apps, schema_editor):
    perms = (
        utils.get_permission_object(
            apps,
            'job_seeker',
            'Document',
            constants.Permissions.add_document.value),
        utils.get_permission_object(
            apps,
            'job_seeker',
            'Document',
            constants.Permissions.view_document.value),
        utils.get_permission_object(
            apps,
            'job_seeker',
            'Document',
            constants.Permissions.delete_document.value),
    )

    job_seeker = models.Group.objects.get(name='job_seeker')
    job_seeker.permissions.add(*perms)

class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0043_add_share_job_permission_to_company_user'),
    ]

    operations = [
        migrations.RunPython(add_perms_to_job_seeker)
    ]
