#!/bin/sh

set -o errexit
set -o pipefail
set -o nounset


python /app/manage.py collectstatic --noinput
/usr/local/bin/gunicorn leet.wsgi --bind 0.0.0.0:5000 --chdir=/app --error-logfile /var/log/gunicorn/error.log --access-logfile /var/log/gunicorn/access.log --log-level debug
