from tests.api_requests.apply import *
from tests.api_requests.auth import *
from tests.api_requests.candidate import *
from tests.api_requests.comment import *
from tests.api_requests.company import *
from tests.api_requests.geo import *
from tests.api_requests.job import *
from tests.api_requests.job_seeker import *
from tests.api_requests.permission import *
from tests.api_requests.public_api import *
from tests.api_requests.subscription import *
from tests.api_requests.survey import *
from tests.api_requests.log import *
from tests.api_requests.notification_center import *
from tests.api_requests.letter_template import *
from tests.api_requests.event import *
