# Generated by Django 2.1 on 2018-08-29 11:04

from django.db import migrations


group_names = ['company_admin', 'job_seeker', 'employer']


def load_groups(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    for group_name in group_names:
        group = Group(name=group_name)
        group.save()


def delete_groups(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.filter(name__in=group_names).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('leet_auth', '0001_initial'),
    ]
    operations = [
        migrations.RunPython(load_groups, delete_groups)
    ]
