# Generated by Django 2.1 on 2018-11-05 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leet_auth', '0002_create_user_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletionReason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, verbose_name='text')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deletion_reason', to='leet_auth.ProxyUser')),
            ],
        ),
    ]
