# Generated by Django 2.1 on 2018-11-08 17:30

from django.db import migrations


def rename_groups_drop_unused(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(name='company_admin').update(name='company_user')
    Group.objects.filter(name='employer').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('leet_auth', '0003_deletionreason'),
        ('permission', '0008_export_job_csv_permissions')
    ]

    operations = [
        migrations.RunPython(rename_groups_drop_unused)
    ]
