# Generated by Django 2.1 on 2018-12-12 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leet_auth', '0004_renamed_auth_groups'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proxyuser',
            options={'verbose_name': 'User'},
        ),
    ]
