# Generated by Django 2.1 on 2019-01-04 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leet_auth', '0005_verbose_name_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deletionreason',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='text'),
        ),
    ]
