# Generated by Django 2.1 on 2018-12-17 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0005_extract_zips'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Countries'},
        ),
    ]
