# Generated by Django 2.1 on 2019-02-25 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0008_null_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('abbreviation', models.CharField(max_length=16)),
                ('utc_offset', models.CharField(max_length=16)),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='timezone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='geo.TimeZone'),
        ),
    ]
