# Generated by Django 2.1 on 2019-03-12 14:00

import os

from django.db import migrations, models

from geo.migrations.data import csv_reader

CURRENT_DIR_PATH = os.path.dirname(os.path.abspath(__file__))
CITIES_CSV_FILE = 'us_cities.csv'
CITIES_CSV_PATH = os.path.join(CURRENT_DIR_PATH, 'data', CITIES_CSV_FILE)


def create_time_zones(apps, schema_editor):
    state_model = apps.get_model('geo', 'State')
    city_model = apps.get_model('geo', 'City')
    states = state_model.objects.prefetch_related('cities').all()
    state_cities = csv_reader.get_cities_from_csv(
        CITIES_CSV_PATH, incorporated='True')
    timezone_cities = {}
    for state in states:
        csv_cities = state_cities[state.abbreviation]
        for city in csv_cities:
            timezone = city['timezone']
            if timezone_cities.get(timezone) is None:
                timezone_cities[timezone] = []
            city_id = state.cities.get(name=city['city']).id
            timezone_cities[timezone].append(city_id)
    for timezone, city_ids in timezone_cities.items():
        city_model.objects.filter(id__in=city_ids).update(timezone=timezone)


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20190312_1400'),
        ('geo', '0011_drop_null_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='timezone',
            field=models.CharField(default='UTC', max_length=255, verbose_name='timezone'),
        ),
        migrations.DeleteModel(
            name='TimeZone',
        ),
        migrations.RunPython(create_time_zones)
    ]
